# Generated by Django 5.1.1 on 2024-09-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDesk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_str',
            field=models.CharField(max_length=30, verbose_name='Состояние задачи'),
        ),
    ]
