# Generated by Django 5.1.1 on 2024-09-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDesk_app', '0002_alter_status_status_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionlevel',
            name='level_code',
            field=models.CharField(default='UNC', max_length=5, verbose_name='Уровень доступа'),
        ),
    ]
